Project_3/Project_3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('account/', include('account.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls, name='adm'),
    path('', TemplateView.as_view(template_name='success.html'), name='success'),

    path('test/', include('testsuite.urls'))

]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_3/account/urls.py
from django.urls import path

from .views import UserAccountLoginView, UserAccountLogoutView, UserAccountUpdateView, CreateUserAccountView, \
    LeaderBoard

app_name = 'account'

urlpatterns = [

    path('register/', CreateUserAccountView.as_view(), name='registration'),
    path('login/', UserAccountLoginView.as_view(), name='login'),
    path('logout/', UserAccountLogoutView.as_view(), name='logout'),
    path('profile/', UserAccountUpdateView.as_view(), name='profile'),
    path('leaderboard/', LeaderBoard.as_view(), name='leaderboard'),

]

Project_3/testsuite/urls.py
from django.urls import path

from .views import TestList, TestRunView, TestPreView

app_name = 'test'

urlpatterns = [

    path('list/', TestList.as_view(template_name='test_list.html'), name='list'),

    path('<int:pk>/question/<int:seq_nr>', TestRunView.as_view(), name='testrun_step'),

    path('<int:id>/', TestPreView.as_view(), name='test preview'),

    # path('<int:pk>/start', StartTestView.as_view(), name='start'),
]

Project_3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>


<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index'%}">Testing project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'test:list'%}">Test Suits <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:leaderboard' %}">Leader board</a>
                </li>

            </ul>

        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">


            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'account:profile'%}">Profile </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout'%}">Logout</a>
                    </li>

                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'account:registration'%}">Register <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login'%}">Login</a>
                    </li>

                {% endif %}
            </ul>

        </div>
    </nav>

    {% if messages %}

    {% for message in messages %}
    {% if message.level == 20 %}
    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>
    {% endif %}
    {% if message.level == 30 %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}


    {% endif %}


    <h3 class="p-4">{{title}}</h3>
    <p></p>
    {% if user.is_authenticated %}
        Logged in
    {% else %}
        Not logged in
    {% endif %}
    <p></p>
    {% block content%}
    {% endblock%}

</div>

</body>
</html>

Project_3/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Start page</h1>

{% endblock %}

Project_3/templates/pagination.html
{% if page_obj.has_other_pages %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <li class="page-item"><a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}</a></li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}

    </ul>
{% endif %}

Project_3/templates/success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Success page!</h1>

{% endblock %}